#!/bin/sh
# Check if rtl_sdr_fm_player is running
if [ "$(pidof rtl_sdr_fm_player)" ]
then
  # If it is running, then switch to the rtl_sdr_fm_player window
  /usr/bin/xdotool search --name 'RTL-SDR FM Player' windowactivate
else
  # If it is not running, then execute it
  /home/pi/software/github/rtl_sdr_fm_player/rtl_sdr_fm_player &
fi
exit 0
